services:
  # Backend API service
  - type: web
    name: redbus-clone-api
    env: node
    buildCommand: cd frontend/server && npm install
    startCommand: cd frontend/server && node index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000

  # Frontend web service
  - type: web
    name: redbus-clone-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm install -g serve && serve -s dist/frontend -l 3000
    envVars:
      - key: API_URL
        sync: false
