services:
  # Backend API service
  - type: web
    name: redbus-clone-api
    env: node
    plan: free
    buildCommand: cd frontend/server && npm install
    startCommand: cd frontend/server && node index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: https://redbus-clone-frontend.onrender.com

  # Frontend static site
  - type: static
    name: redbus-clone-frontend
    buildCommand: |
      npm install -g @angular/cli@17.3.0
      cd frontend
      npm install
      ng build --configuration production
    publishPath: frontend/dist/frontend
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: API_URL
        value: https://redbus-clone-api.onrender.com
