services:
  # Backend API service
  - type: web
    name: redbus-clone-api
    env: node
    plan: free
    region: oregon
    buildCommand: cd frontend/server && npm install
    startCommand: cd frontend/server && node index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000

  # Frontend static site
  - type: web
    name: redbus-clone-frontend
    env: node
    plan: free
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s dist/frontend -l $PORT
    envVars:
      - key: API_URL
        sync: false
      - key: PORT
        value: 10000
